spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://52.221.188.170:3306/hr
    password: pass@1234
    username: user1
  jpa:
    show-sql: true
server:
  port: 9001
  servlet:
    context-path: /employees
logging:
  file:
    name: employees-ws.log